Gho 3/basic search script/search
marcpires/git-bash-hands-on pull request #8
Opened 2021-01-06 13:00 UTC by alecio-rocha

Implementing a search script

2021-01-06 13:09 UTC, marcpires approved these changes
LGTM

2021-01-06 13:09 UTC, marcpires commented on search.sh
> +fi
EOF

2021-01-06 13:09 UTC, marcpires commented on search.sh
> +            find ~/ -name FILE      #comando a ser executado
Here you also could use the $HOME environment variable

2021-01-06 16:53 UTC, alecio-rocha commented on search.sh
> +            find ~/ -name FILE      #comando a ser executado
I ended up changing it to the $ HOME variable, but I left a comment about the two forms.

2021-01-06 17:04 UTC, alecio-rocha commented on search.sh
> +fi
EOF correction, but when sending to the GIT repository the last line was removed.

2021-01-08 12:55 UTC, marcpires requested changes

2021-01-08 12:55 UTC, marcpires commented on search.sh
> +if [ $# -eq 0 ]; then
would not be better to ask for the search term if user does not pass it as a parameter ?

Instead of notify and exit to:
- Use the search term if user pass it as parameter
-  If no script parameter is passed, ask user to inform it from stdin (read FILE)

2021-01-08 19:42 UTC, alecio-rocha commented on search.sh
> +# Script básico que recebe um argumento e procura o arquivo no diretorio HOME.
Change to English. :D

2021-01-08 19:43 UTC, alecio-rocha commented on search.sh
> +        echo "Você utilizou mais de 1 argumento!!"
Converted to English.

2021-01-08 19:45 UTC, alecio-rocha commented on search.sh
> +if [ $# -eq 0 ]; then
implementation changes.

2021-01-11 12:45 UTC, marcpires commented on search.sh
> +    echo "Enter at least one argument: "
If you use -n the echo command does not add a new line

2021-01-11 12:47 UTC, marcpires approved these changes
LGTM

2021-01-11 13:05 UTC, marcpires requested changes
---

2021-01-11 14:01 UTC, alecio-rocha commented on search.sh
> +    echo "Enter at least one argument: "
modification according to the comment.

2021-01-11 14:14 UTC, marcpires approved these changes
LGTM

2021-01-11 14:17 UTC, merged